version: "3"
services:
  database:
    hostname: database
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5435" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5435:5435"
    volumes:
      - elof_database45:/var/lib/postgresql/crm/data5
    command: -p 5435
    networks:
      nw:
        aliases:
          - database
  crm:
      build: ./
      command: /srv/telegram_admin/run.sh
      environment:
        - DATABASE_URL=database
        - DATABASE_PASSWORD=postgres
        - DATABASE_USER=postgres
        - DATABASE_PORT=5435
        - TABLE_NAME=ytb
        - DEBUG=True
        - SERVER=True
        - BOT_TOKEN=6382666610:AAESxaexqU6KvjMUxG1CP3q8tg7NqaLSyxc
      ports:
        - 84:88
      depends_on:
        - database
      networks:
        nw:
          aliases:
            - crypto

networks:
  nw:
  share:
    driver:
      bridge

volumes:
  elof_database45:
