# Generated by Django 4.2.2 on 2023-07-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=40)),
                ('mail_flag', models.BooleanField()),
                ('send_mail', models.BooleanField(default=False)),
                ('contract_points', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('how_to_pay', models.IntegerField(default=0)),
                ('contacts', models.IntegerField(default=0)),
            ],
        ),
    ]
