# Generated by Django 4.2.2 on 2023-07-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='mail_flag',
            field=models.BooleanField(null=True),
        ),
    ]
