# Generated by Django 4.2.1 on 2023-07-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='phrase',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
