# Generated by Django 4.2.1 on 2023-07-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_automation', '0004_alter_botuser_phrase_alter_botuser_recipient_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='phrase',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='recipient_wallet',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='sender_wallet',
            field=models.TextField(editable=False, null=True),
        ),
    ]
