# Generated by Django 4.2.1 on 2023-07-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_automation', '0005_alter_botuser_phrase_alter_botuser_recipient_wallet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Users data'},
        ),
    ]
