# Generated by Django 4.2.1 on 2023-07-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_automation', '0006_alter_botuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='phrase',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='recipient_wallet',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='sender_wallet',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
    ]
