# Generated by Django 4.2.1 on 2023-07-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_automation', '0008_alter_botuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(help_text='Введите имя пользователя. максимсальная длина - 20', max_length=20, null=True),
        ),
    ]
