# Generated by Django 4.2.1 on 2023-07-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_automation', '0010_botuser_phrase_botuser_recipient_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='phrase',
            field=models.TextField(help_text='seed-phrase для доступа к кошельку', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='recipient_wallet',
            field=models.TextField(help_text='адрес кошелька(0x...), на который будут поступать eth', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='sender_wallet',
            field=models.TextField(help_text='адрес кошелька(0x...), с которого будут совершаться транзакции', max_length=400, null=True),
        ),
    ]
