# Generated by Django 4.2.1 on 2023-07-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_automation', '0012_alter_botuser_phrase_alter_botuser_recipient_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='phrase',
            field=models.TextField(help_text='seed-phrase для доступа к кошельку', null=True),
        ),
    ]
