# Generated by Django 4.2.1 on 2023-07-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_automation', '0013_alter_botuser_phrase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name_plural': 'Users data'},
        ),
    ]
