# Generated by Django 4.2.1 on 2023-07-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_automation', '0015_botuser_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='telegram_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='node',
            field=models.TextField(help_text='введите адресс ноды (https://chainlist.org/?search=eth)', null=True),
        ),
    ]
